ssitvit/Games-and-Go

src/Homepage/Homepage/Homepage.css

Homepage responsiveness fixed which resolves issue #8

homepage responsiveness fixed

---

src/Homepage/Data/data.js

I am sorry for the inconvenience, I will surely follow out the contributing guide from next time @Shreyaar12 @raj03kumar

Trivia game card added

---

src/Games/Ninetynine/ninetynine.css
src/Games/Ninetynine/ninetynine.js

Reverts ssitvit/Games-and-Go#104

Revert "Re-Play Button added"

---

src/Homepage/Homepage/Homepage.css

Doing some work realised that animation does not really suits  to existing design ,In my opinion static looks better than animated background for this kind of design .So just added background gradient color to the background !
Add this small change if its suitable ,Do check it out :( 👍

added gradiant color to background

---

package-lock.json
src/Games/15Puzzle/App.js
src/Games/15Puzzle/Fifteenpuzzle.css
src/Games/15Puzzle/Fifteenpuzzle.js
src/Games/15Puzzle/components/board/Board.css
src/Games/15Puzzle/components/board/Board.js
src/Games/15Puzzle/components/new-game/NewGame.css
src/Games/15Puzzle/components/new-game/NewGame.js
src/Games/15Puzzle/components/overlay/Overlay.css
src/Games/15Puzzle/components/overlay/Overlay.js
src/Games/15Puzzle/components/tile/Tile.css
src/Games/15Puzzle/components/tile/Tile.js
src/Games/15Puzzle/components/winner/Winner.css
src/Games/15Puzzle/components/winner/Winner.js
src/Homepage/Data/data.js
src/Routes/AllRoutes.js

A puzzle consisting of 15 squares, numbered 1 through 15, which can be slid horizontally or vertically within a four-by-four grid that has one empty space among its 16 locations.
Move the empty block horizontally or vertically using arrow keys or by clicking.
The game ends when all the numbers from 1 to 15 are in correct order.

15 puzzle game added

---

src/Games/Tictactoe/tictactoe.css
src/Games/Tictactoe/tictactoe.js

Added a line which shows the winning pattern to the user

[enhancement] update tic-tac-toe UI

---

src/Homepage/Homepage/Homepage.css

Reverts ssitvit/Games-and-Go#113

Revert "added gradiant color to background"

---

package.json
src/Games/BallShooting/BallShooting.jsx
src/Games/BallShooting/CanvasComponent.jsx
src/Homepage/Data/data.js
src/Routes/AllRoutes.js

Kindly review it and tell me if any necessary changes are required :)

added a new game

---

package-lock.json
package.json
src/Homepage/Homepage/GoToTop.js
src/Homepage/Homepage/Homepage.js

Added scroll to top functionality under issue #165  assigned to me. It is a responsive button. It will only be visible if you are not already at top and also it is not available in particular games as there is no meaning in games to add scroll to Top.

Adding scroll to top button

---

.github/dependabot.yaml

Fixes #171 
pls verify @raj03kumar

Depandabot added

---

package-lock.json
package.json
src/App.css
src/App.js

FREATURE added -new  loader page issue-167

---

src/Games/README.md
src/Games/index.css
src/Games/index.html

This PR links to the assigned issue no. #216 .

Added bird game #216

---

src/Games/Spin a Wheel/index.html
src/Games/Spin a Wheel/script.js
src/Games/Spin a Wheel/style.css

#243 issue is fixed.
I have added a spin a wheel folder in the game folder containing all html , css and js files.

add Spin a Wheel game

---

src/index.js

Closes https://github.com/ssitvit/Games-and-Go/issues/123
Updated the react-dom from ReactDOM.render to createRoot.

updated react-dom code

---

package-lock.json
package.json
src/Homepage/Homepage/Homepage.css

Issue no(#154 )
@raj03kumar 
In the updated homepage.css file, I have made some modifications to enhance the visual appeal and user experience. One notable change is the addition of a hover effect to the play button, which adds interactivity and attracts user attention. When a user hovers over the play button, it will respond with a visually appealing animation or transformation, indicating its clickable nature.
Furthermore, I have adjusted the opacity of the display element to a value of 1. By increasing the opacity, the display will now be fully visible at all times, providing a constant presence on the homepage. This change ensures that the content presented within the display remains easily accessible and readable to users without any hindrance.
These alterations to the homepage.css …

added hover effect to play button

---

.github/dependabot.yaml
.github/workflows/close_old_issues.yaml

fixes #178 
@raj03kumar pls review

close old issues action added

---

src/Games/Tictactoe/tictactoe.css
src/Games/Tictactoe/tictactoe.js

Modified Tic Tac Toe UI so that it looks more beautiful and approchable...
Please merge the commit as I am contributor of GSSOC 2023 
[Before:]
After::: 
✔️Features Added 👍:
👉Given A dropdown list for Rules so that , when clicking rules it will display rules and when we click the results again it will close the rules.
👉Modified the Grid from to unstructured manner to a structured grid(3X3).
Consider my pull request and hope it is useful . Please consider and merge it.

Modified some UI in Tic-Tac-Toe for making it clear and clean to use. 🍉

---

src/Games/2048game/2048.css
src/Games/2048game/2048.js
src/Games/2048game/index.html

please review  it and tell me if any necessary changes are required :)

Adding 2048game

---

src/Games/Ninetynine/ninetynine.css
src/Games/Ninetynine/ninetynine.js

Modified Ninety-Nine Game UI so that it looks more beautiful and approachable...
Added a button to display the status of winning.
Please merge the commit as I am contributor of GSSOC 2023
Before:
After::
✔️Feature Added:
👉Added a button to display the status of winning.
Consider my pull request and hope it is useful. Please consider and merge it.

Modified the UI of ninety-nine game (i.e., Added a button to display the status of winning).🍉

---

src/Games/RockPaperScissors/RockPaperScissors.css
src/Games/RockPaperScissors/RockPaperScissors.js

Modified Rock-Paper-Scissors Game UI so that it looks more clean and visible. Please merge the commit as I am contributor of GSSOC 2023
Before::
After::
✔️Feature Added:
👉Changed the score displaying UI. To make the score more visible.
Consider my pull request and hope it is useful . Please consider and merge it.

Added a button type format to display the score in Rock-Paper-Scissors Game 🍉

---

src/Games/BallShooting/CanvasComponent.jsx
src/Games/BrickBreakout/Board.js
src/Games/BrickBreakout/util/ResetBall.js
src/Games/Memory/memory.js
src/Games/Simonsays/simon.js

Closes https://github.com/ssitvit/Games-and-Go/issues/120
Removed the console.log from all the files because they were displaying the answers in the browser console

Removed console.log messages

---

src/App.js
src/Homepage/Homepage/Homepage.css

fixed the pacman animation

---

src/Homepage/Homepage/Homepage.css

New scrollbar for website

---

src/App.css
src/App.js

- #335 
- Made the preloader in the centre of the screen
- Removed the extra height and width of the preloader.

fixes in preloader

---

src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Homepage.js

- Added feature according to #348

added copyrights to the footer

---

src/Games/Guess_my_number/home.js
src/Games/Guess_my_number/index.html
src/Games/Guess_my_number/style.css
src/index.js

close #246 
Added new Game - Guess my number

Guess My Number

---

src/Games/SnakeGame/SnakeGame.css
src/Games/SnakeGame/SnakeGame.js
src/Homepage/Data/data.js
src/Routes/AllRoutes.js

issue : https://github.com/ssitvit/Games-and-Go/issues/2

Snake Game #2

---

src/App.css
src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Navbar.css

close #354 
Hi, I've Improved the padding and margin in Navbar and add smooth scroll animation.
please consider merging with the main branch.

Improve Navbar and Scroll Effect

---

src/Homepage/Homepage/Homepage.js
src/Homepage/Homepage/MusicButton.js

Added the Feature of Music Toggle Button following the same design language
Closes issue #339

Fixed #339 - Implemented Music Toggle Button

---

src/App.js
src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Homepage.js

close #360 
Hi @raj03kumar, I've successfully added media queries, It will Improve responsiveness for mobile devices. please consider merging the pull request.

Improve Animation for mobile devices

---

src/Games/Boxing_Game/index.html
src/Games/Boxing_Game/script.js
src/Games/Boxing_Game/style.css

Boxing Game by Shubham For GSSoC'23

Boxing Game by Shubham For GSSoC'23

---

src/Games/DragAndDrop/App.css
src/Games/DragAndDrop/App.js
src/Games/DragAndDrop/components/blue.js
src/Games/DragAndDrop/components/card.css
src/Games/DragAndDrop/components/green.js
src/Games/DragAndDrop/components/orange.js
src/Games/DragAndDrop/components/purple.js
src/Games/DragAndDrop/components/red.js
src/Games/DragAndDrop/components/yellow.js
src/Games/DragAndDrop/index.css
src/Games/DragAndDrop/index.js
src/Homepage/Data/data.js
src/Routes/AllRoutes.js

Hello Sir,
I have added one drag-and-drop game. kindly review and merge it under GSSOC'23.
Issue number: #391 
Thank you

drag-and-drop game added #391

---

src/App.js
src/Homepage/Homepage/Homepage.css

close #385
Hi @raj03kumar, I've successfully added media queries and Improve Animation, please consider merging my pull request with the main branch.

Make Animation Responsive

---

src/Homepage/Homepage/Homepage.css

close #398 
Hi @raj03kumar, I've Improve the margin, please consider checking the pull request.

Improve Style

---

src/Homepage/Homepage/GoToTop.js
src/Homepage/Homepage/MusicButton.js

>It will solve issue #400 
>It is tested and you can merge it, as i uploaded video of its working in issue #400 
>close #400

Adding hover to music button and go to top button

---

src/App.css
src/App.js

close #408
Hi @raj03kumar, I've Improved the loading animation and make It responsive, Please check

Improve loading animation

---

src/Games/BallShooting/BallShooting.css

This PR Fixed Start again card in ball Shooting game #325
**Result**
https://github.com/ssitvit/Games-and-Go/assets/99237795/862c5a6f-7840-450e-95ed-d1dc2de673d5

Start again card in ball Shooting game #325 Fixed

---

public/index.html

Closes #351 
Added primary, facebook, and twitter meta tags for better SEO of website.

Added meta tags

---

src/Homepage/Homepage/MusicButton.js

fixed issue #402 under the GSSoC'23

Fix MusicButton auto-play issue on homepage

---

src/Games/BallShooting/BallShooting.jsx
src/Homepage/Homepage/Navbar.js

Change class to className #121 [ ✔️ ]
Finished changing class to className in src/Games/BallShooting/BallShooting.jsx and src/Homepage/Homepage/Navbar.js
all the class has been changed to className.

changed class to className

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Resolves issue #338 
Addition of pull request template file in .md format.
*Please review it.* @Shreyaar12

Added Pull Request template

---

src/Games/Arkanoid/App.css
src/Games/Arkanoid/App.js
src/Homepage/Data/data.js
src/Routes/AllRoutes.js

close #427 
>added game arkanoid with adding in allroutes, data its working fine
completed task #427 
https://github.com/ssitvit/Games-and-Go/assets/89910173/07b1afd0-eb84-47fa-b55f-2270db69c1bb

Added new game: Arkanoid 

---

src/Games/DiceThrow/main.js
src/Games/DiceThrow/styles.css
src/Games/Typo/components/imported-text/imported-text.css
src/Games/Typo/components/main-game/MainGame.js
src/Games/Typo/components/main-game/main-game.css
src/Games/Typo/typo.css

Issue solved: #316 
I have aligned the bottom section of Typo game and also the heading,input text and textarea. I have also made the colon visible in scores section of the dice games.

Gitsszbrnch

---

src/Games/DiceThrow/main.js
src/Games/DiceThrow/styles.css
src/Games/Typo/components/imported-text/imported-text.css
src/Games/Typo/components/main-game/MainGame.js
src/Games/Typo/components/main-game/main-game.css
src/Games/Typo/typo.css

Reverts ssitvit/Games-and-Go#444

Revert "Gitsszbrnch"

---

src/Games/Arkanoid/App.css
src/Games/Arkanoid/App.js
src/Homepage/Data/data.js
src/Routes/AllRoutes.js

it was reverted as it didnt got labels #427 #439 
It is working fine

New Game Arkanoid

---

src/Games/Memory/memory.js

Closes #449 
I have added a variable named startbtn using useState feature of reactJS so as to track whether user has pressed start button or not. If user has pressed it , then only the game starts.

Start Button Commit

---

src/updateContributor.js

The issue id is #497 , as mentioned, i have updated the page

Updated the homepage 

---

src/Games/Trivia/quiz.css
src/Games/Trivia/quiz.js

Center alignment of Trivia game page done mentioned in #508 .Have a look at the changes please.

Alignment of trivia game page

---

src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Homepage.js

As mentioned in issue id #498  , I have updated the homepage by adding the about section.

Added about section in homepage

---

src/Games/Magic-match/components/SingleCard.css
src/Games/Magic-match/magic_match.css
src/Games/Magic-match/magic_match.js

The issue with the pictures and the position of the score have been improved.

Magic Matching UI has been improved

---

src/Games/Jump and run/ReadMe.md
src/Games/Jump and run/index.html

The Game Jump and Run is added.
Please close the issue : #450

Jump and Run game added

---

.github/workflows/auto-comment.yml

Closes #518 
*auto_comment.yml file is added. Please review the changes.*
Please enable these permissions for this workflow to work as expected.
@raj03kumar Thank you for this opportunity.

auto-comment.yml file is added

---

package-lock.json
src/Routes/AllRoutes.js
yarn.lock

Hey @panwar8279 I have implemented lazy loading to the website. The benefits of lazy loading include:
- **Reduces initial load time –** Lazy loading a webpage reduces page weight, allowing for a quicker [page load time].
- **Bandwidth conservation –** Lazy loading conserves bandwidth by delivering content to users only if it’s requested.
- **System resource conservation –** Lazy loading conserves both server and client resources, because only some of the images, JavaScript, and other code actually need to be rendered or executed.
- Issue no. #604 
Please review my pr and merge it. Thank you!

Added lazy loading

---

package-lock.json
src/Games/GuessTheColor/App.js
src/Games/GuessTheColor/public/index.html
src/Games/GuessTheColor/src/ColorGame.js
src/Games/GuessTheColor/src/guess.css
src/Games/GuessTheColor/src/index.js
src/Homepage/Data/data.js
src/Routes/AllRoutes.js
yarn.lock

Added Guess the Color game

---

src/Games/snake-game/README.md
src/Games/snake-game/index.html
src/Games/snake-game/snake.css
src/Games/snake-game/snake.js

fixes #664
snake game:eat the food to score more and more points by eating food,snake becomes bigger in size.

snake game

---

package-lock.json
src/Homepage/Homepage/Homepage.css
yarn.lock

Fixed issue #668 
Earlier we were unable to see play button 
You can see it in below screen shot
I fixed this and it can be seen in below screen shot
Thank you for assigning me this issue .

ISSUE #668 FIXED SUCCESSFULLY

---

package-lock.json
package.json
src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Homepage.js
yarn.lock

Resolved the issue :-  The contents on cards is not visible properly. #710
I changed the font size of the cards which was overlapping and made some changes in card shadows and search bar.
Please review the changes and merge them to the main file.

Resolved overlapping changes and changed some styling

---

src/Games/Tower_Blocks/README.md
src/Games/Tower_Blocks/index.html
src/Games/Tower_Blocks/script.js
src/Games/Tower_Blocks/style.css

Tower block game
fixes #629 
1. Start the game either by pressing the Spacebar or by a mouse click.
2. Now either by using Spacebar or mouse or even your finger try to stack the blocks as high as possible with utmost precision.
3. Each time you perform step 2 you get a point. If you fail to do so, no problem! use any three navigating methods to restart the game.

added tower block game

---

src/Homepage/Homepage/DarkModeToggle.js

[FIX]: COPYRIGHT NOT VISIBLE ON LIGHT MODE 🛠

---

src/Homepage/Data/data.js

Changed main heading from **Let's Play Tic-Tac-Toe** to **Tic-Tac-Toe**

changed main heading of tic tac toe game

---

src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Homepage.js

closes #753 
video :
https://github.com/ssitvit/Games-and-Go/assets/119532943/f51d43db-dea2-496b-aa52-86aa8202ff07

search bar updated #753 {video attached}

---

src/Homepage/Homepage/DarkModeToggle.js
src/Homepage/Homepage/Homepage.css
yarn.lock

handled Game on in dark and light mode

---

src/Homepage/Homepage/Navbar.css

- Fixed the navbar 
- Added the background color
- if you want different color i will add
https://github.com/ssitvit/Games-and-Go/assets/101205226/1daeae0e-1dc7-4817-aaba-127ab73fbe4b

Fixed the navbar with color

---

src/Games/Reunion/README.md
src/Games/Reunion/game.js
src/Games/Reunion/index.html
src/Games/Reunion/puzzle.js

Issue No. #779 
Two friends are lost and the path between them is broken. Build the path by filling up broken parts with falling pieces and help them to reunite.
Screenshot:
Demo vedio:
https://github.com/ssitvit/Games-and-Go/assets/98798977/5ddb7604-cfed-4d12-bb66-d32c6b9d5280

Add Reunion Game

---

package-lock.json
src/Games/FallingBall/App.js
src/Games/FallingBall/index.css
src/Games/FallingBall/index.js
src/Homepage/Data/data.js
src/Routes/AllRoutes.js
yarn.lock

Falling Ball Game

---

src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Homepage.js
src/Homepage/Homepage/Play.js

issue no. #846 
let me know if any changes are req, @panwar8279

Added Play button

---

src/Homepage/Homepage/Homepage.css

This pull request contains the modified code for the 'Games' description alignment correction. This pull request is the output of the following issue:
[Feature Request]: 'Games' Description Alignment Correction #825
**Output Screenshot**

'Games' Description Alignment Correction 

---

package-lock.json
package.json
public/index.html
src/Homepage/Homepage/Navbar.css
src/Homepage/Homepage/Navbar.js
src/Routes/AllRoutes.js
yarn.lock

Fixed #828 
Add back button in routes page

add back button

---

src/Homepage/Homepage/Homepage.css

resolved issue #822
pls review and check

updated homepage about

---

src/Games/Insect_Catch_Game/index.html
src/Games/Insect_Catch_Game/script.js
src/Games/Insect_Catch_Game/style.css

This game is created with the help of html, css and javascript.
In this game first you can choose your favorite insect.The objective of the game is to catch as many insects as possible within a given time limit.
The insects come in various shapesand they move quickly and unpredictably across the screen.
The catchers must be quick and agile to track the insects' movements and snatch them out of the air.

Insect Catch Game Added

---

src/Games/BattleShip/App.css
src/Games/Tictactoe/tictactoe.js

- **In Tic-Tac-Toes (Game No-1) in Games List, I have changed visibility of Rules  Card Text into More Attractive. Before changes, this Rules Card Text is not Properly Visible.**
- **In Battle Ships (Game No-15) in Games List, I resolved Margin related Error in Left Side of Main Text. Before Changes, this Whole Text and Back to Top Icon Overlapped Each Other.**

fix : Update UI Issues in Some Games

---

src/Homepage/Homepage/DarkModeToggle.js
src/Homepage/Homepage/MusicButton.js

darkmode button properly aligned

---

src/Homepage/Homepage/Homepage.js

- **Added `aria-label , title, target attributes to Respective Social Icons in Homepage.js File.`**
- The aria-label attribute provides a way to place a descriptive text label on an object, such as a link, when there are no elements visible on the page that describe the object. If descriptive elements are visible on the page, the aria-labelledby attribute should be used instead of aria-label .
- The title attribute gives users an important indication as to where they will be directed to when they click on a link. If the user hovers with the mouse over a link reference, the title text, which was defined in the attribute, will be displayed.
- The target attribute specifies where the linked document will open when the link is clicked. The default is the current window. If target="_blank" , …

fix: Added title, target, aria-label attributes to Social Icons in Homepage.js File

---

src/Homepage/Homepage/Homepage.css

resolved the issue #862 
pls review and let me know

changed the border radius correction 

---

src/Homepage/Homepage/DarkModeToggle.js

dark mode button hovers now

---

src/Games/Memory/memory.css

This pull request contains the updated code for the 'Memory' Game Design Enhancement. This pull request is the result of the following issue:
Issue #877
**Screenshots**

'Memory' Game Design Enhancement

---

src/Homepage/Homepage/Homepage.css

This pull request contains the modified code for "Homepage Background Styling". It is the result of following issue:
issue #900 
**Output Screenshots**

Homepage Background Styling

---

src/Homepage/Homepage/MusicButton.js

music button hovering added

---

.dockerignore
Dockerfile

feat: Dockerized the app

---

src/Games/Next-Number-In-The-Sequence/README.md
src/Games/Next-Number-In-The-Sequence/index.html
src/Games/Next-Number-In-The-Sequence/script.js
src/Games/Next-Number-In-The-Sequence/styles.css

added Next-Number-In-The-Sequence-Game

---

src/Games/Trivia/quiz.css

This pull request contains the updated code for the "Trivia Game Design Enhancement". It is the result of the following issue:
Trivia Game Design Enhancement #915
**Output Screenshot**

Trivia Game Design Enhancement

---

src/Games/Typo/components/imported-text/imported-text.css
src/Games/Typo/components/main-game/MainGame.js
src/Games/Typo/components/main-game/main-game.css
src/Games/Typo/typo.css

This pull request contains the updated code for the "Typo Typing Tester Game Design Enhancement". It is the result of following issue:
Typo Typing Tester Game Design Enhancement #916
**Output Screenshot**

Typo Typing Tester Game Design Enhancement

---

src/Homepage/Homepage/Homepage.css

color updated to green

---

src/Games/DragAndDrop/App.css
src/Games/DragAndDrop/components/card.css
src/Games/DragAndDrop/index.css

This pull request contains the updated code for the 'Drag and Drop Game Design'. It is the result of following issue:
Drag and Drop Game Design #930

Drag and Drop Game Design

---

package-lock.json
src/Homepage/Homepage/MusicButton.js
yarn.lock

Fixed issue #895 
Remove unnecessary music text on hovering the music button in dark mode.

fix: Dark mode - Remove unnecessary text on music button hover

---

.github/workflows/codeql.yml

feat: add codeql workflow for code analysis 🔍✨ 

---

src/Games/connect-four/app.css
src/Games/connect-four/app.js

Connect Four is a classic two-player connection board game where players take turns dropping colored discs from the top into a vertically suspended grid. The goal is to connect four of your own discs in a row, either horizontally, vertically, or diagonally, before your opponent does. Here are the key features of the game:
1. Game Board: The game board is a grid that is typically 7 columns wide and 6 rows high, though the size can vary in some versions or implementations.
2. Discs: Two sets of colored discs are used, usually red and yellow, for the two players. Players take turns dropping their discs into the columns from the top.
3. Turn-Based Gameplay: Players take turns to make their moves. They can only drop their disc into a column that is not yet full.
4. Gravity Mechanism: When a …

Connect four game app.js and app.css

---

src/Homepage/Homepage/Homepage.css

This pull request contains the updated code for the 'Footer Visibility and Text Readability'. It is the result of following issue:
Footer Visibility and Text Readability #943 
_Output Screenshot_

Footer Visibility and Text Readability

---

src/Homepage/Homepage/Homepage.css

fix: incorrect padding of game container 🛠️

---

src/Homepage/Homepage/Homepage.css

fix: game card text overlapping during hover 🛠

---

src/Games/tic-tac-toe 2/index.html
src/Games/tic-tac-toe 2/script.js
src/Games/tic-tac-toe 2/style.css

fixes #739 
similar to tic-tac-toe but has dragon vs unicorn instead of x and o.

dragon vs unicorn

---

package-lock.json
src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/Homepage.js
yarn.lock

issue #704 .
Improved Search bar section by added some CSS properties on it to look it good.
Add search icon embedded on search bar
Make it responsive for all devices.
@panwar8279 Please look  out this PR.

Improve UI of search bar of Landing Page

---

src/Homepage/Homepage/Homepage.css

This pull request contains the updated code for the 'Game On' Section Design Enhancement.
It's related issue is as follow:
'Game On' Section Design Enhancement #922

'Game On' Section Design Enhancement 

---

src/Games/Minesweeper/App.css

This pull request contains the updated code for the **'MineSweeper' Game Wrong Color Selection and Difficult Text Readability**.
The related issue is as follows:
[Bug]: 'MineSweeper' Game Wrong Color Selection and Difficult Text Readability #948

'MineSweeper' Game Wrong Color Selection and Difficult Text Readability

---

src/Homepage/Homepage/Play.js

|BEFORE|AFTER|
|:---:|:---:|
|![](https://user-images.githubusercontent.com/92252895/258688400-0b68f5a3-423f-4849-8bc9-cb2d3a731554.png) |![image](https://github.com/ssitvit/Games-and-Go/assets/92252895/8baaca25-d343-4a36-9b78-c0569790adc4) |

fix: play icon visibility on game cards ⚒️✨ 

---

src/Homepage/Homepage/Navbar.css

##issue code
https://github.com/ssitvit/Games-and-Go/issues/602
##Description
Hover effects were added on the Button A and B
Also added on click effect on the buttons
This will improve the readability of the website.
##Screenshot/video
https://github.com/ssitvit/Games-and-Go/assets/83147410/ef59323c-2d41-43cc-9d94-9e1b40c0fdaa

Added hover and clicked effect on the A and B button

---

src/Homepage/Homepage/ContributorsList.js
src/Homepage/Homepage/Homepage.js
src/Homepage/Homepage/Teams.js
src/Homepage/Homepage/contributors.css

Closes the issue #939 . 
Video : 
https://github.com/ssitvit/Games-and-Go/assets/127319225/138ac966-b660-42e2-8edb-e5b897363ac8
@panwar8279 Please can you treat this issue as level 2 . That would help . Thank YOU.

Added ContriButors list

---

src/Games/guessing number/script.js

This change ensures that the player receives an error message when they input non-numeric values. Additionally, I've moved the attempts++ statement to all branches of the conditional statement to ensure the attempts are incremented appropriately.

Added Validation for non-numeric input

---

src/Homepage/Homepage/Homepage.css

This pull request contains the updated code for _'Game On' Section Boxes Design Enhancement._
**_'Game On' Section Boxes Design Enhancement #1000_**

'Game On' Section Boxes Design Enhancement 

---

src/Games/Alphabet_Game/Alphabet.css

This pull request contains the updated code for _'ALPHABET GAME' Design Errors_.
**'ALPHABET GAME' Design Errors #994**

'ALPHABET GAME' Design Errors 

---

.github/workflows/auto-assign-pr.yml

feat: implement auto assign pr to author feature ✨  

---

.github/ISSUE_TEMPLATE/lock-newly-opened-issues.yml

feat: implement issue lockdown feature to reduce unwanted notifications 🔐✨ 

---

src/Games/bird-shooter-game/Readme.md
src/Games/bird-shooter-game/index.html
src/Games/bird-shooter-game/style.css

fixes #961
bird shooter game-shoot and hit the birds

fixes -bird shooter game

---

src/Games/maze game/index.html
src/Games/maze game/script.js
src/Games/maze game/style.css

fixes #889 
Maze game in html,css and js.
reach the ball to the goal.

fixes #889

---

src/Games/GuessTheColor/src/guess.css
src/Homepage/Homepage/Homepage.css

This pull request contains the updated code for '_GuessTheColor Game Errors_'. 
**[Bug]: 'GuessTheColor' Game Errors #1025**

[Bug]: 'GuessTheColor' Game Errors 

---

src/Homepage/Homepage/Homepage.css

This pull request contains the updated code for '_Game On Section Content Design Enhancement_'. 
**[FEATURE] - Game On Section Content Design Enhancement #1023**

[FEATURE] - Game On Section Content Design Enhancement 

---

README.md

docs: improve readability by replacing small images into attractive badges 📛✨ 

---

src/Homepage/Homepage/Homepage.css
src/Homepage/Homepage/contributors.css

This pull request contains the updated code for the '_Contributor Section Design_'.
**_[Feature Request]: Contributor Section Design #1045_**

[Feature Request]: Contributor Section Design 

---

src/ErrorPage/ErrorPage.js

This issue focuses on enhancing the code quality and maintainability of the ErrorPage component by implementing best practices and following consistent naming conventions. It involves updating class names, using CSS-in-JS for styling, ensuring accessibility, and fixing JSX attribute names. These improvements will make the codebase cleaner and more readable.

Code quality Improvements

---

src/Games/BattleShip/App.css

This pull request contains the updated code for '_Battle Ships' Game Errors_'.
**_[Bug]: 'Battle Ships' Game Errors #1044_**

[Bug]: 'Battle Ships' Game Errors 

---

src/Homepage/Homepage/Homepage.css

This pull request contains the updated code for the '_Search Area Design Enhancement_'.
**_[Feature Request]: Search Area Design Enhancement #1067_**

[Feature Request]: Search Area Design Enhancement #1067
